Backend tests for file upload endpoints
opengovsg/postmangovsg pull request #1192
Opened 2021-05-12 04:45 UTC by miazima

## Problem

Closes #1165 and closes #1166

## Solution

- Add tests for file upload and upload status routes for email, protected email and telegram channels

2021-05-20 08:15 UTC, lamkeewei requested changes
@miazima - we need to also test the different scenarios of the file parsing successes/errors as stated in #1165.

Some of the missing scenarios are:
- Invalid recipient list with missing params
- Ensure that messages are populated correctly in the respective messages table from uploading a valid recipient list

For these cases, we will need to mock the file download from S3.

2021-06-07 03:05 UTC, miazima commented
I have added on missing scenarios, however the tests involving the file processing in `...-template.middleware.test.ts` are failing intermittently, am trying to figure what is causing it

2021-06-15 01:51 UTC, miazima commented on backend/src/sms/middlewares/tests/sms-template.middleware.test.ts
> +    )
The following asserts on the sms messages table being populated fails, I suspect due to the async `parseAndProcessCsv` not having completed running. However this sleep function does not seem to resolve the issue. Similar issue for the telegram template middleware.

2021-06-15 01:51 UTC, miazima commented on backend/src/core/services/redis.service.ts
> +}
Added this close function to wait for the redis connections to close, this did not resolve the open handles issue, unless the implementation is flawed?

2021-07-27 07:08 UTC, lamkeewei commented
To close in favour of #1202

2022-07-25 03:55 UTC, closed without merging

2022-07-26 05:17 UTC, stanleynguyen commented
Outdated due to #1202 implementation