Add space after email salutation in the email template body
opengovsg/postmangovsg pull request #1221
Opened 2021-06-07 09:03 UTC by miazima

## Problem

When there is no space following the email salutation, in templates such as below, the email preview tends to look phishy.

```
Dear form admin,You are receiving this email because
```

Closes #1149 

## Solution

**Improvements**:

- Add a space after the first comma in the email template, ensuring that there is a space followed by words
- Make this change after sanitising the template body 

e.g.
```
Dear form admin, You are receiving this email because
```

## Before & After Screenshots

**BEFORE**:
<img src="https://user-images.githubusercontent.com/5744384/120971267-060a5500-c79f-11eb-8234-011ba834044a.png" width="50%">
<img src="https://user-images.githubusercontent.com/5744384/120971296-0c003600-c79f-11eb-92cb-828944cf4484.png" width="50%">

**AFTER**:
<img src="https://user-images.githubusercontent.com/5744384/120984577-60121700-c7ad-11eb-8c8b-232d076b4ca7.png" width="50%">
<img src="https://user-images.githubusercontent.com/5744384/120987431-2989cb80-c7b0-11eb-90ad-c34bc87732c8.png" width="50%">

## Tests

- Enter template `Dear form admin,You are receiving this email because` 
- Save template and observe the preview to see that there is now a space after the email salutation

2021-06-14 07:58 UTC, lamkeewei requested changes
Regex don't account for cases where the following block is not a `p` tag. Also might be good to extend out tests to cover different cases for this new functionality.

2021-06-14 07:58 UTC, lamkeewei commented on backend/src/email/services/email-template.service.ts
> +  sanitizedBody = sanitizedBody.replace(/(^.+?,)([^\s].+?<\/p>.*)/, '$1 $2')
This regex seems to have an issue if the next block after email salutation is not a `p` tag. See [here](https://regex101.com/r/J2YEpo/1) for example.

2021-06-15 09:17 UTC, miazima commented
> Actually, I had to separately implement this functionality while implementing the preheader feature as part of stripping the content of all HTML tags ([see this block](https://github.com/opengovsg/postmangovsg/pull/1217/files#diff-2527711556c19ec518189ee7b3162dc95c0de2605c84373bad4fca69252b170aR28-R41)), so we might no longer need this regex

@mjgui Oh was working on correcting the regex and adding tests. Perhaps I can help write tests for your implementation?

2021-06-15 09:28 UTC, mjgui commented
Oh yeah sure! Though I probably need to refactor the method into a separate function so it's more testable haha

2021-06-24 04:45 UTC, lamkeewei commented
@mjgui and @miazima is this PR still required?

2021-06-30 05:30 UTC, closed without merging