Email template logos
opengovsg/postmangovsg pull request #1263
Opened 2021-06-30 11:12 UTC by mjgui

## Problem

Current emails are mostly in plaintext, making them seem like phishing emails. Additionally, they carry no branding of the agency that sent the emails.

Closes [#1203, #1216]

## Solution

_Note: HTML theme is still TBC, waiting for design to be finalised_
- Implemented a HTML template for future emails which includes agency name (in the footer) and agency logo
- Updated `agencies` table to include `name` and `logo_uri` columns, add `domains` table to store mappings from domains to agencies
- Added backend logic to lookup agency details based on reply_to value
- Updated existing email preview to use same styles 

## Before & After Screenshots
_Note: Copy in screenshots is outdated_

**Desktop View**

<img src="https://user-images.githubusercontent.com/9080115/121170595-016d9b80-c888-11eb-9559-3afb78489104.png" width="500"/>

**Mobile View**
<img src="https://user-images.githubusercontent.com/9080115/121160756-f19d8980-c87e-11eb-8a9d-ff344e1218f5.png" width="300"/>

**Rich text Edtior**
<img src="https://user-images.githubusercontent.com/9080115/122186539-b6bfd500-cec0-11eb-9429-0af23b9e0846.png" width="500"/>

## Tests

- Send out any email - email should be sent using the new theme
- Draft a new email campaign - rich text editor should be using Arial font (in black), email preview (in step 2 and 4) should show the new theme

## Deploy Notes

- Motivation behind new schema is [here](https://github.com/opengovsg/postmangovsg/issues/1203#issuecomment-852788863)

```
cd backend && npx sequelize db:migrate
```

**When we want to add Logo support**
Note: For now, we can skip the following two steps (populate agencies and logos) until we finalise the logos. This PR only needs the above schema changes to run and will work even if the new tables are blank.

- [ ] Populate list of agencies and domains, populate existing users with domains

- [ ] After populating domains, backpatch existing users table with domains (if valid)
```sql
UPDATE users 
  SET email_domain = d.domain
  FROM domains d
  WHERE SUBSTR(users.email, POSITION( '@' in users.email ) )  = d.domain;
```

2021-07-05 04:04 UTC, mjgui commented
The commit history is kinda messy becaused I based this branch off #1217 
Will fix when squashing and merging...

2021-07-05 16:06 UTC, lamkeewei requested changes
Let's add some tests for the changes before merging this in.

2021-07-05 16:06 UTC, lamkeewei commented on backend/src/database/migrations/20210630070237-add-columns-to-agencies.js
> +    await queryInterface.dropTable('agencies')
Just a comment, I guess this is ok since agency table is empty now.

2021-07-06 05:48 UTC, jeantanzj commented
```
Jean  12 minutes ago
my concern is that we might create the domain nillywilly then validate the domain (edited) 

Jean  11 minutes ago
is it possible to put the domain .gov.sg in the domains table for validation, instead of using the env var? (edited) 

Gui Ming Jiang  11 minutes ago
I believe both hooks need to pass for the user to be created (edited) 

Jean  10 minutes ago
if populateDomain runs before validateEmail, there’s no check on whether the email ends with .gov.sg . we could put them in the same function for strict ordering? btw the hooks dont currently run in a transaction (edited) 

Gui Ming Jiang  9 minutes ago
Hm.. I suppose adding .gov.sg to the DB works, but it might not be clear to whoever's reading the code that that's the intention

Gui Ming Jiang  7 minutes ago
Oh I thought by passing in options.transaction into findOrCreate it should tie it up with the user transaction

Gui Ming Jiang  7 minutes ago
Then if validateEmail throws an error, it will stop the user creation action

Jean  4 minutes ago
prior to the addition of the agencies table, there was no need for a transaction because we weren’t looking up the db, just the env var.
right now validateDomain(email) should have options.transaction passed in as well.
I’m not sure if I am getting my point across, or if I’ve misinterpreted the code:
If validateEmail runs before populateDomain, when someone enters blah@abc.com , we would reject abc.com
If populateDomain runs before validateEmail, we would create abc.com in domains, then validate the email, and consequently accept abc.com (edited) 

Jean  2 minutes ago
the part about adding .gov.sg to the domains table is a separate issue - it’s so that we don’t have too many entrypoints to keep track of. Or at least remove specific domains from the env var?
```

2021-07-06 05:53 UTC, jeantanzj commented
@mingjiang  https://www.postgresql.org/docs/9.5/transaction-iso.html
>13.2.1. Read Committed Isolation Level
Read Committed is the default isolation level in PostgreSQL. When a transaction uses this isolation level, a SELECT query (without a FOR UPDATE/SHARE clause) sees only data committed before the query began; it never sees either uncommitted data or changes committed during query execution by concurrent transactions. In effect, a SELECT query sees a snapshot of the database as of the instant the query begins to run. **However, SELECT does see the effects of previous updates executed within its own transaction, even though they are not yet committed.** Also note that two successive SELECT commands can see different data, even though they are within a single transaction, if other transactions commit changes after the first SELECT starts and before the second SELECT starts.

2021-07-06 05:55 UTC, jeantanzj commented
@lamkeewei 
that's true, we should change https://github.com/opengovsg/postmangovsg/blob/dde8fe82edddf8533b6ad587fdb17833bc9dc635/backend/src/core/services/auth.service.ts#L265-L269

2021-07-06 06:03 UTC, lamkeewei commented on backend/src/core/models/domain.ts
> +  static async populateAgency(
Let's combine this with the `validateEmail`. We shouldn't rely on the implicit ordering of the execution of the hooks. In addition, the same transaction should also be passed to `validateDomain`. My bad for not seeing there was an additional hook above.

2021-07-07 06:33 UTC, mjgui commented on backend/src/core/models/user/tests/user.test.ts
> +  await RedisService.shutdown()
Btw, the Redis clients aren't shutting down for me locally (though Travis still passes it)...
Not sure how to fix this

2021-07-07 07:39 UTC, mjgui commented on backend/src/core/models/user/tests/user.test.ts
> +  await RedisService.shutdown()
Also, not sure if I've covered all the cases for this test

2021-07-07 07:42 UTC, mjgui commented on backend/src/core/utils/validate-domain.ts
>        action: 'validateDomain',
In the end I didn't remove this log since presumably the env var should be quite short

2021-07-07 07:42 UTC, mjgui commented on frontend/src/components/dashboard/create/email/EmailTemplate.tsx
> +              </p>
Actually not sure if it's a concern that the `<label>` tag is only in the first para

2021-07-07 09:53 UTC, mjgui commented on backend/src/core/utils/validate-domain.ts
> +  if (dbDomain != null) {
Tbh I don't know LOL, but if `sequelize-typescript` is trusted I guess it doesn't matter

2021-07-07 10:58 UTC, lamkeewei approved these changes
lgtm! Tested the following scenarios:

- User with `email_domain`, `agency` and `domain` configured should be shown their agency logo and can send mail including it
- Toggling show logo to “off” should not include logo in sent email
- User with `email_domain = NULL` should not have access to option to include logo option. Sending should work as expected.
- User with `email_domain` set to a domain linking to an agency with an empty `logo_uri` should not have access to option to include logo
- User whose domain does not exist yet, should have it’s domain automatically created on login

2021-07-07 11:09 UTC, merged