refactor: users data model
opengovsg/postmangovsg pull request #1832
Opened 2022-10-09 09:03 UTC by tan-zx

wip

2022-10-09 11:55 UTC, tan-zx commented on backend/src/core/models/user/user-credential.ts
> -  cred!: Credential
deleting this as it is dead code

2022-10-10 06:15 UTC, tan-zx commented
PENDING: to test on staging first (will remove this comment when done)

2022-10-11 03:00 UTC, stanleynguyen requested changes
This can't be released this way, as there will be a gap after u have done the migration, but the new code haven't deployed yet - resulting in all API key related operations failing.
Please break this PR down to:
- a migration to creating a new column called `api_key_hash` with a trigger to insert this value to be the same as `api_key`
- backfill all existing `api_key` values to corresponding `api_key_hash` values
- deploy the new code
- another migration removing `api_key` field and the trigger from step (1)

2022-10-11 06:21 UTC, tan-zx commented
> This can't be released this way, as there will be a gap after u have done the migration, but the new code hasn't been deployed yet - resulting in all API key related operations failing. Please break this PR down to:
> 
> * a migration to creating a new column called `api_key_hash` with a trigger to insert this value to be the same as `api_key`
> * backfill all existing `api_key` values to corresponding `api_key_hash` values
> * deploy the new code
> * another migration removing `api_key` field and the trigger from step (1)

ohhh good point — will do!

2022-10-21 06:48 UTC, stanleynguyen approved these changes

2022-10-21 06:58 UTC, merged