Richardyak/feat/render hyperlinks
opengovsg/postmangovsg pull request #1863
Opened 2022-11-07 05:56 UTC by richard-yak

## Problem

Hyperlinks in E-mails were not rendering as clickable hyperlinks.

## Solution

This solution will read the column header of the templated field, and if the field ends with "_url" or "_link", will automatically wrap the field with a tags so that the HTML on the E-mail can render as hyperlinks

## To Note
In future as we have more "template rules", can easily refactor here to check based on column strings and handle accordingly using switch cases or a new function.

2022-11-07 15:47 UTC, stanleynguyen commented
Can we
![](https://i.imgflip.com/6zujfx.jpg)

It's worth adding a test case to `tests/templating/template-client.test.ts`

2022-11-07 15:48 UTC, stanleynguyen requested changes
Can we
![](https://i.imgflip.com/6zujfx.jpg)

It's worth adding a test case to `tests/templating/template-client.test.ts`

2022-11-08 02:32 UTC, richard-yak commented
@stanleynguyen done adding test cases, plz re-review

2022-11-08 02:37 UTC, stanleynguyen approved these changes

2022-11-08 03:03 UTC, merged