feat: incremental release of whatsapp, basic apis
opengovsg/postmangovsg pull request #2029
Opened 2023-05-15 01:56 UTC by richard-yak

Included in this release

- Adding of basic APIs required by a new channel, such as credentials, get campaigns, and their relevant validators
- Adding models files that were in the previous PR's schema changes.
- Adding DTO mappers for whatsapp related responses
- Adding migration files for supporting models, independent to the whatsapp feature

Upcoming releases
- Basic UI updates to support a new channel
- Campaign updates to support a new channel
- Step by step release for whatsapp, and their relevant backend supporting APIs

2023-05-16 08:12 UTC, stanleynguyen requested changes

2023-05-16 08:12 UTC, stanleynguyen commented on backend/src/core/services/domain.service.ts
> +  if (user == null) {
*`===`

2023-05-16 08:12 UTC, stanleynguyen commented on backend/src/whatsapp/middlewares/whatsapp.middleware.ts
> +      res.sendStatus(401)
Let's have a response body that follows our standard fields of `code` and `message` fields. Come back to this after the refactor is merged in for error responses

2023-05-16 08:12 UTC, stanleynguyen commented on backend/src/whatsapp/middlewares/whatsapp.middleware.ts
> +      res.sendStatus(400)
Similarly about error reponse

2023-05-16 08:12 UTC, stanleynguyen commented on backend/src/whatsapp/middlewares/whatsapp.middleware.ts
> +      res.sendStatus(401)
Similarly about error response

2023-05-16 08:12 UTC, stanleynguyen commented on backend/src/whatsapp/middlewares/whatsapp.middleware.ts
> +      res.sendStatus(400)
Similarly about error responses

2023-05-16 08:12 UTC, stanleynguyen commented on backend/src/whatsapp/models/campaign-whatsapp-template.ts
> +  @Column(DataType.INTEGER)
INT or BIGINT?

2023-05-16 08:12 UTC, stanleynguyen commented on backend/src/whatsapp/routes/whatsapp-settings.routes.ts
> +  router.get('/phone-numbers', whatsappMiddleware.getPhoneNumbers)
Where are the request validators?

2023-05-16 08:12 UTC, stanleynguyen commented on backend/src/whatsapp/services/whatsapp-callback.service.ts
> +  // although this is a nested loop, in practice it is only 1 entry
This comment is a bit ambiguous, could u elaborate?

2023-05-16 08:12 UTC, stanleynguyen commented on shared/src/clients/whatsapp-client.class/index.ts
> +    })
Please dont mix `async/await` with `then/catch`

2023-05-16 08:12 UTC, stanleynguyen commented on shared/src/clients/whatsapp-client.class/index.ts
> +      throw new Error(res)
Can the message be more specific than the stringified `res`? Like `Error(res.message)` or something (this is just a shot in the dark as I'm not aware of the structure of this obj

2023-05-16 08:12 UTC, stanleynguyen commented on shared/src/clients/whatsapp-client.class/index.ts
> +    }
Same as the bunch of comments above

2023-06-08 02:06 UTC, tan-zx commented
removing myself from the review — will relook at this after it's clearer what we need to build for SGC is!

2023-06-15 01:54 UTC, closed without merging