fix: bugs in whitelisting script
opengovsg/postmangovsg pull request #2205
Opened 2023-08-28 02:31 UTC by KishenKumarrrrr

## Problem

- `update_whitelist.ts` : The previous script added all users regardless of whether or not they are part of the experimental feature.
- `insert_experimental_govsg_user.ts` : The previous script did not check to see whether or not the user should be deleted from the DB. 

## Solution

- `update_whitelist.ts` : When querying users, we do so from the `GovsgTemplatesAccess` table instead of `Users` table.
- `insert_experimental_govsg_user.ts` : Perform an extra check on the `to remove` column of the CSV file (5th column). If this value is `'Y'`, we do not add the user to the DB.

## Deployment Checklist

NA

2023-08-28 03:14 UTC, jia1 commented
I'm a bit confused over why we query from `GovsgTemplatesAccess`:

If we want to care if a user is part of the experimental feature, we should be querying the `user_experimental`

2023-08-28 03:23 UTC, jia1 commented
I also noticed the script is rather complex for what it's aiming for. I would normally expect a db call for each set of users:

First, get all GOVSG users. Give them access to the templates.

Then, get all MCI GOVSG folks. Give them access to the MCI templates.

Finally, get all OGP GOVSG folks. Give them access to the OGP templates.

This is so we don't need to do additional steps like:

```
  const ogpOfficers = agencyUsersToUpdate.filter(
    (u) => u.user.email.split('@')[1] === 'open.gov.sg'
  )
```

and:

```
const allUsers = [...agencyUsersToUpdate, ...usersToUpdate]
```

which are easily missed out and require tracing. I understand that there's some performance tradeoff but it could be worth it if we want to make this easily readable for everyone running the script.

2023-08-28 03:24 UTC, jia1 approved these changes

2023-08-30 07:51 UTC, jia1 commented on backend/src/scripts/whitelisting/constants.ts
> +  'sgc_notify_upcoming_call_2',
Just noticed: We gonna use `sgc_notify_upcoming_call_3`.

2023-11-25 13:07 UTC, joshualiangxy requested changes

2024-02-23 02:16 UTC, KishenKumarrrrr commented
We no longer need to do this.

2024-02-23 02:16 UTC, closed without merging